### ISSUE TITLE
Extend identifier regex

### ISSUE THREAD

**Issue by promgamer** [d-led/influxdb-cpp-rest#11]
According to [influxDB docs](https://docs.influxdata.com/influxdb/v1.4/introduction/getting_started/):

> Names of databases can contain any unicode character as long as the string is double-quoted. Names can also be left unquoted if they contain only ASCII letters, digits, or underscores and do not begin with a digit.

So this is valid:
 `CREATE DATABASE mydb`, which is supported right now.

This is invalid:
 `CREATE DATABASE my-db`

But this is valid (and not supported right now):
 `CREATE DATABASE "my-db"`.

**Comment by d-led** [comment]
Ok. In case you have a PR, go ahead.

**Comment by d-led** [comment]
I'll try to get to it otherwise

**Comment by d-led** [comment]
I had to extend the regex a bit to include quoted double quotes and exclude non-quoted ones. I hope, you don't mind.

**Comment by d-led** [comment]
There will be some discrepancy between the check and the influxdb set of allowed identifiers, but the api should error on invalid identifier on queries anyways
