### ISSUE TITLE
Bool not handled correctly

### ISSUE THREAD

**Issue by maxlein** [d-led/influxdb-cpp-rest#20]
Hi, 

it seems boolean values are not handled correctly.  
When I pass a boolean as value to my line, I get an invalid boolean error and the line strings looks like its wrongly parsed as a number: `charge_conductor=falsei`

But I am wondering if nobody ever recognized this..

**Comment by d-led** [comment]
It seems, booleans will need a specialization. Feel free to submit a PR if you get to it faster

**Comment by d-led** [comment]
@maxlein check out the latest commit, whether it solves your problem
