### ISSUE TITLE
No authentication

### ISSUE THREAD

**Issue by nikkov** [d-led/influxdb-cpp-rest#3]
Hi, it's interesting project, because there is no C++ drivers in last versions influxdb. But, this library can't be used if authentication is enabled on InfluxDB.

**Comment by d-led** [comment]
@nikkov yes, this would be a nice feature. If you can do it, go ahead! If not, I'll get to it once I have time

**Comment by d-led** [comment]
implementation hints: [1](https://github.com/Microsoft/cpprestsdk/issues/3#issuecomment-147528272), [2](https://stackoverflow.com/a/31519995/847349)

**Comment by d-led** [comment]
there are [2 options]:(https://docs.influxdata.com/influxdb/v1.2/query_language/authentication_and_authorization/#authenticate-requests) basic authentication or query parameters. Both are valid, but basic authentication is the preferred method
