### ISSUE TITLE
set timestamp

### ISSUE THREAD

**Issue by nikkov** [d-led/influxdb-cpp-rest#4]
Not supported [timestamp](https://docs.influxdata.com/influxdb/v1.2/write_protocols/line_protocol_tutorial/#timestamp)  parameter in insert.
I'm sorry, I'm only getting acquainted with InfluxDB and Rest API, so I can not realize this features myself yet.

**Comment by d-led** [comment]
Ok! Have you tried the library already?

**Comment by nikkov** [comment]
I just modify yours demo.cpp code for experiments with library and InfluxDB

**Comment by d-led** [comment]
test now run successfully on travis-ci and appveyor
