### ISSUE TITLE
writing multiple points

### ISSUE THREAD

**Issue by nikkov** [d-led/influxdb-cpp-rest#6]
Library not support [writing multiple points](https://docs.influxdata.com/influxdb/v1.2/guides/writing_data/#writing-multiple-points)

**Comment by d-led** [comment]
It's done with the async api. There's no need to do it manually, in my view. The async api batches multiple points automatically

**Comment by d-led** [comment]
[multiple points implementation detail](https://github.com/d-led/influxdb-cpp-rest/blob/master/src/influxdb-cpp-rest/influxdb_simple_async_api.cpp#L60)

**Comment by nikkov** [comment]
But in some cases needed insert many measurements with sync API, but maybe you are right. 
Some time ago I tried the InfluxDB.Net library and expected to see such an approach in this library too.

**Comment by d-led** [comment]
you could actually do it using the sync api as well, as the only dependency is on the `line` class, which can be replaced, as the parameter name in [the simple api](https://github.com/d-led/influxdb-cpp-rest/blob/master/src/influxdb-cpp-rest/influxdb_simple_api.cpp#L47) suggests.

But  I will consider a simple way to create multiple lines, e.g. 

```cpp
line(....)
& line (....)
```
