### ISSUE TITLE
Compiling with MSVC 2015 generates libraries that need MSVCP120D.dll

### ISSUE THREAD

**Issue by LiosanGOG** [d-led/influxdb-cpp-rest#9]
As in the subject line, the solution file build/influxdb-cpp-rest.sln when compiled with MSVC 2015 creates libraries that require the debug DLLs from MSVC 2012?

This is my first experience with Nuget, but it seems the project explicitly requiests both v120 and v140 packages for cpprestsdk?

Liosan

**Comment by d-led** [comment]
I haven't looked at the cpprestsdk binaries yet. You might want to look with the dependency walker, whether your resulting binary really needs the v120d runtime, as nuget packages contain may contain binaries for multiple targets. I'll take a look soon

**Comment by d-led** [comment]
both debug and release 64 bit executables seem to depend on the correct runtimes.

I'm closing the issue, but if you like, you can describe in detail how you compiled the libraries (starting from the checkout), and what the [Dependency Walker](http://www.dependencywalker.com/) output looks like

![image](https://user-images.githubusercontent.com/1716584/33245045-797e676e-d302-11e7-88e4-1bf04c35ef9e.png)

![image](https://user-images.githubusercontent.com/1716584/33245061-a8373b08-d302-11e7-8c90-05f91d7bf503.png)
